owner: tron4x
git-repo: https://github.com/tron4x/portworx-umbrella
charts-repo: https://tron4x.github.io/portworx-umbrella
release-name-template: "{{ .Name }}-{{ .Version }}"
make-release-latest: true
generate-release-notes: true
release-notes-header: |
  ## Portworx Umbrella Chart {{ .Version }}
  
  ### Changes
