{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "portworx-monitoring.fullname" . }}-servicemonitor
  labels:
    {{- include "portworx-monitoring.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      name: portworx-api
  endpoints:
  - port: px-api
    interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
    path: /metrics
{{- end }}
