{{- if .Values.deployOperator }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portworx-operator.serviceAccountName" . }}
  namespace: {{ include "portworx-operator.namespace" . }}
  labels:
    {{- include "portworx-operator.labels" . | nindent 4 }}
{{- if (semverCompare "<1.25" (.Capabilities.KubeVersion.GitVersion | regexFind "^v\\d+\\.\\d+\\.\\d+"| trimPrefix "v"))}}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: px-operator
spec:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  volumes:
    - secret
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
{{- end }}
---
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: {{ include "portworx-operator.fullname" . }}
  labels:
    {{- include "portworx-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  {{- if (semverCompare "<1.25" (.Capabilities.KubeVersion.GitVersion | regexFind "^v\\d+\\.\\d+\\.\\d+"| trimPrefix "v"))}}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["px-operator"]
    verbs: ["use"]
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  name: {{ include "portworx-operator.fullname" . }}
  labels:
    {{- include "portworx-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "portworx-operator.serviceAccountName" . }}
    namespace: {{ include "portworx-operator.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "portworx-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portworx-operator.fullname" . }}
  namespace: {{ include "portworx-operator.namespace" . }}
  labels:
    {{- include "portworx-operator.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      {{- include "portworx-operator.selectorLabels" . | nindent 6 }}
      name: portworx-operator
  template:
    metadata:
      labels:
        {{- include "portworx-operator.selectorLabels" . | nindent 8 }}
        name: portworx-operator
    spec:
      containers:
        - name: portworx-operator
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
          image: {{ template "portworx-operator.imageRegistry" . }}:{{ .Values.pxOperatorImageVersion | default .Chart.AppVersion }}
          command:
            - /operator
            - --verbose
            - --driver=portworx
            - --leader-elect=true
          env:
            - name: OPERATOR_NAME
              value: portworx-operator
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                      - portworx-operator
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: {{ include "portworx-operator.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.registrySecret .Values.registrySecret }}
      imagePullSecrets: 
      - name: {{ .Values.global.registrySecret | default .Values.registrySecret }}
      {{- end }}
{{- end }}
