{{- if not .Values.disableStorageClass }}
{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  labels:
    {{- include "portworx-storageclasses.labels" $ | nindent 4 }}
provisioner: pxd.portworx.com
parameters:
  {{- toYaml .parameters | nindent 2 }}
allowVolumeExpansion: {{ .allowVolumeExpansion | default true }}
reclaimPolicy: {{ .reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ .volumeBindingMode | default "Immediate" }}
{{- end }}

{{- if .Values.storkSnapshotClass.enabled }}
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.storkSnapshotClass.name }}
  labels:
    {{- include "portworx-storageclasses.labels" . | nindent 4 }}
snapshotter: pxd.portworx.com
parameters:
  {{- toYaml .Values.storkSnapshotClass.parameters | nindent 2 }}
reclaimPolicy: {{ .Values.storkSnapshotClass.reclaimPolicy | default "Delete" }}
{{- end }}
{{- end }}
