name: Chart Testing

on:
  pull_request:
    paths:
      - 'charts/**'
      - 'Chart.yaml'
      - 'values.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ["1.28.9"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Create kind cluster
        run: |
          # Install kind
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          
          # Create cluster
          kind create cluster --name kind --image kindest/node:v${{ matrix.k8s-version }}
          kubectl cluster-info

      - name: Install CRDs (with size limit handling)
        run: |
          # Try to install CRDs, skip if too large
          for crd in crds/*.yaml; do
            echo "Installing CRD: $crd"
            if ! kubectl apply -f "$crd"; then
              echo "Warning: CRD $crd failed to install (possibly too large), continuing..."
            fi
          done

      - name: Run chart-testing (install)
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} \
            --helm-extra-set-args "--set=global.imageRegistry=docker.io --set=global.clusterName=test-cluster"

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run helm-docs
        run: |
          docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Documentation is outdated. Please run helm-docs and commit changes!'
            exit 1
          fi
