name: Chart Testing

on:
  pull_request:
    paths:
      - 'charts/**'
      - 'Chart.yaml'
      - 'values.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: ["1.29.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v${{ matrix.k8s-version }}
          cluster_name: kind

      - name: Install CRDs
        run: kubectl apply -f crds/

      - name: Run chart-testing (install)
        run: |
          ct install --target-branch ${{ github.event.repository.default_branch }} \
            --helm-extra-set-args "--set=global.imageRegistry=docker.io --set=global.clusterName=test-cluster"

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run helm-docs
        run: |
          docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Documentation is outdated. Please run helm-docs and commit changes!'
            exit 1
          fi
