name: Chart Testing

on:
  pull_request:
    paths:
      - 'charts/**'
      - 'Chart.yaml'
      - 'values.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.14.0'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Template Charts (validation only)
        run: |
          helm template test-release . \
            --set global.imageRegistry="docker.io" \
            --set global.clusterName="test-cluster" \
            --set monitoring.enabled=false

      - name: Validate Chart Templates
        run: |
          # Test all sub-charts individually
          helm template test-operator charts/portworx-operator \
            --set global.imageRegistry="docker.io"
          
          helm template test-software charts/portworx-software \
            --set global.imageRegistry="docker.io" \
            --set global.clusterName="test-cluster"
          
          helm template test-storageclasses charts/portworx-storageclasses \
            --set global.imageRegistry="docker.io"
          
          helm template test-monitoring charts/portworx-monitoring \
            --set global.imageRegistry="docker.io"

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run helm-docs
        run: |
          docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:latest
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Documentation is outdated. Please run helm-docs and commit changes!'
            exit 1
          fi
